baseurl = "https://suizman.org"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "suizman.org"
disqusShortname = "suizman"


[author]
name = "Martin Evgeniev"

[params]
  description = "Homepage and blog"
  keywords = "homepage, blog, science, informatics, development, programming"
  contentTypeName = "posts"
  defaultTheme = "light"
  customCSS = ["/css/custom.css"]

  [params.logo]
    logoText = "$ echo Zdravei"
    logoHomeLink = "/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/SuizVanderplug"

  [[params.social]]
    name = "github"
    url  = "https://github.com/suizman"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/suizman"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
