name: Publish site on GitHub Pages (master branch)

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone current repo
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup Timezone
      run: |
        sudo timedatectl set-timezone Europe/Madrid
        sudo dpkg-reconfigure --frontend noninteractive tzdata
    - name: Fetch hugo and build static site
      run: |
        ./build.sh
    - name: Publish static site on master branch
      run: |
        cd public
        git init
        git remote add origin "https://github.com/${{ github.repository }}.git"
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m 'Auto build'
        git -c http.https://github.com/.extraheader="AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.GITHUB_TOKEN }} | base64 --wrap=0)" push -f origin master
